### ISSUE TITLE
dt is not a function

### ISSUE THREAD

**Issue by Nikamura** [auth0/auth0-react#474]
Using auth0-react together with docusaurus, it was working fine but after upgrade to `1.12.1` from `1.12.0` build started failing during server side rendering stage.

with error:
```
TypeError: dt is not a function
```

**Comment by frederikprijck** [comment]
Can you verify the error is gone again when downgrading to 1.12.0?

If so, could you provide some reproduction steps, or a minimal application integrating the two to reproduce the behavior?

I can't seem to reproduce it with a typical react application, so it would help for us to reproduce and look into it.

**Comment by Nikamura** [comment]
Yeah, it works with 1.12.0. I will try to reproduce it with minimal setup.

**Comment by Nikamura** [comment]
I was unable to reproduce with fresh docusaurus project and after upgrade to auth0 react 2.0.0 the error isn't there.
