### PR TITLE
Fix Typescript compilation for 4.6.3

### LINKED ISSUE #811: Typescript compilation error
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

My project uses Typescript 4.6.3. This library fails to compile with these errors.

```
node_modules/@auth0/auth0-react/src/utils.tsx:22:20 - error TS2339: Property 'error' does not exist on type 'object'.

22       typeof error.error === 'string'
                      ~~~~~

node_modules/@auth0/auth0-react/src/utils.tsx:26:22 - error TS2339: Property 'error_description' does not exist on type 'object'.

26         typeof error.error_description === 'string'
                        ~~~~~~~~~~~~~~~~~

node_modules/@auth0/auth0-react/src/utils.tsx:28:37 - error TS2339: Property 'error' does not exist on type 'object'.

28         return new OAuthError(error.error, error.error_description);
                                       ~~~~~

node_modules/@auth0/auth0-react/src/utils.tsx:28:50 - error TS2339: Property 'error_description' does not exist on type 'object'.

28         return new OAuthError(error.error, error.error_description);
                                                    ~~~~~~~~~~~~~~~~~

node_modules/@auth0/auth0-react/src/utils.tsx:30:35 - error TS2339: Property 'error' does not exist on type 'object'.

30       return new OAuthError(error.error);

```

### Reproduction

1. Clone auth0-react
2. Change typescript version to 4.6.3 in package.json
3. Change moduleResolution to node in tsconfig.json
4. npm install
5. npx tsc -b
6. See errors

```
src/utils.tsx:22:20 - error TS2339: Property 'error' does not exist on type 'object'.

22       typeof error.error === 'string'
                      ~~~~~

src/utils.tsx:26:22 - error TS2339: Property 'error_description' does not exist on type 'object'.

26         typeof error.error_description === 'string'
                        ~~~~~~~~~~~~~~~~~

src/utils.tsx:28:37 - error TS2339: Property 'error' does not exist on type 'object'.

28         return new OAuthError(error.error, error.error_description);
                                       ~~~~~

src/utils.tsx:28:50 - error TS2339: Property 'error_description' does not exist on type 'object'.

28         return new OAuthError(error.error, error.error_description);
                                                    ~~~~~~~~~~~~~~~~~

src/utils.tsx:30:35 - error TS2339: Property 'error' does not exist on type 'object'.

30       return new OAuthError(error.error);
                                     ~~~~~


Found 5 errors.
```

### Additional context

_No response_

### auth0-react version

2.2.1

### React version

17.0.2

### Which browsers have you tested in?

Other

### PR DESCRIPTION
**Pull request by steaks**
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Fixes #811. This PR fixes compilation for on Typescript 4.6.3. It still works on 4.9. 

I tried the simplest solution - casting the variable to the known type.

### References

> Include any links supporting this change such as a:
>
> -#811
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.

### Testing

1. Change typescript version to 4.6.3 in package.json
2. Change moduleResolution to node in tsconfig.json
3. npm install (may need to clean first)
4. npx tsc -b
5. See no compilation errors

Developed on Ubuntu 22.04.5 LTS. Tested in Chrome 129.0.6668.58 (Official Build) (64-bit). Tested in Firefox 131.0.3 (64-bit).

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not the default branch

### CODE REVIEW

**Comment by steaks** [comment]
Hey Auth0 team. It's been a month since I created this PR. I'm not sure what to do here. Should I close this PR or reach out to someone for a review?

**Review by gyaneshgouraw-okta — APPROVED** [review]

**Comment by gyaneshgouraw** [comment]
Closing this as duplicate PR has been merged https://github.com/auth0/auth0-react/pull/896 , which had commits signed.
